云台初始化不旋转

diff --git a/.github/workflows/sync.yaml b/.github/workflows/sync.yaml
--- a/.github/workflows/sync.yaml
+++ b/.github/workflows/sync.yaml
@@ -1,54 +1,47 @@
 name: Sync Local Repository
 
 on:
-  schedule:
-    - cron: '37 13 * * *' # 每小时运行一次
-  push:
-    branches:
-      - main
+  # schedule:
+  #   - cron: '2 * * * *' # 每小时运行一次
+  # push:
+  #   branches:
+  #     - main
 
 jobs:
-  # sync:
-  #   runs-on: ubuntu-latest
+  sync:
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #   - name: Checkout repository
-  #     uses: actions/checkout@v2
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  #   - name: Set up Git
-  #     run: |
-  #       git config --global user.name ${{ secrets.USERNAME }}
-  #       git config --global user.email ${{ secrets.EMAIL }}
+      - name: Set up Git
+        run: |
+          git config --global user.name "${{ secrets.USERNAME }}"
+          git config --global user.email "${{ secrets.EMAIL }}"
 
-  #   - name: Sync with local repository
-  #     run: |
-  #       git remote add local /path/to/your/local/repository
-  #       git fetch local
-  #       git merge local/main
-  #       git push https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/Cofallen/OMNI_C.git main
+      - name: Sync with local repository
+        run: |
+          git remote add local /path/to/your/local/repository || true  # Prevent failure if remote already exists
+          git fetch local
+          git merge local/main
+          git push https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/Cofallen/OMNI_C.git main
 
   upload:
     runs-on: ubuntu-latest
 
     steps:
       - name: 检出代码
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
-      - name: 设置 Git 用户信息
+      - name: Set up Git
         run: |
-          git config --global user.name ${{ secrets.USERNAME }}
-          git config --global user.email ${{ secrets.EMAIL }}
+          git config --global user.name "${{ secrets.USERNAME }}"
+          git config --global user.email "${{ secrets.EMAIL }}"
 
       - name: 添加更改
         run: |
           git add .
-
-      - name: 提交更改
-        run: |
           git commit -m "update" || echo "没有更改需要提交"
-
-      - name: 推送到 GitHub
-        run: |
-          git push origin main
-        env:
-          GITHUB_TOKEN: ${{ secrets.PAT }}
+          git push https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/Cofallen/OMNI_C.git main
+          echo "上传到远程仓库"
